resources:
- name: repo
  type: git
  source:
    uri: "https://github.com/hostaur/restExamples.git"

jobs:
- name: build
  plan:
    - get: repo
      trigger: true
    - task: build
      file: repo/pipeline/test.yml